import { isNull, isUnknown } from '../shape.js'
import type { ShapeNode } from '../types.js'
import type { CodegenSnapshot } from './types.js'

const HEADER = `// Generated by schemind — do not edit by hand.\n// Run \`schm codegen --target msw\` to regenerate.\nimport { http, HttpResponse } from 'msw'\n`

const HTTP_METHODS = new Set(['get', 'post', 'put', 'delete', 'patch', 'options', 'head'])

/**
 * Produce a representative mock JSON value for a shape — one element for arrays,
 * the first non-null branch for unions, placeholder scalars.
 */
export function mockFromShape(node: ShapeNode): unknown {
  switch (node.kind) {
    case 'scalar':
      return node.type === 'string'
        ? 'string'
        : node.type === 'number'
          ? 0
          : node.type === 'boolean'
            ? false
            : null
    case 'array':
      return isUnknown(node.items) ? [] : [mockFromShape(node.items)]
    case 'object': {
      const out: Record<string, unknown> = {}
      for (const [key, child] of Object.entries(node.fields)) out[key] = mockFromShape(child)
      return out
    }
    case 'union': {
      const nonNull = node.types.find((t) => !isNull(t))
      return nonNull ? mockFromShape(nonNull) : null
    }
  }
}

/**
 * Generate an [MSW](https://mswjs.io) handlers module from observed snapshots —
 * test mocks that stay in sync with the API's real shapes.
 */
export function generateMsw(snapshots: readonly CodegenSnapshot[]): string {
  const handlers = snapshots.map((snap) => {
    const { method, path } = parseEndpoint(snap.endpoint)
    const mock = reindent(JSON.stringify(mockFromShape(snap.shape), null, 2), '    ')
    return `  http.${method}('${path}', () => {\n    return HttpResponse.json(${mock})\n  })`
  })

  return `${HEADER}\nexport const handlers = [\n${handlers.join(',\n')},\n]\n`
}

/** Endpoint → MSW method + path (origin stripped, `:id` placeholders kept). */
function parseEndpoint(endpoint: string): { method: string; path: string } {
  const space = endpoint.search(/\s/)
  const rawMethod = (space === -1 ? 'get' : endpoint.slice(0, space)).toLowerCase()
  const method = HTTP_METHODS.has(rawMethod) ? rawMethod : 'all'
  let path = space === -1 ? endpoint : endpoint.slice(space + 1)
  try {
    path = new URL(path).pathname
  } catch {
    /* already a relative path */
  }
  return { method, path }
}

/** Re-indent every line after the first by `pad` (to nest a JSON literal in code). */
function reindent(json: string, pad: string): string {
  return json
    .split('\n')
    .map((line, i) => (i === 0 ? line : pad + line))
    .join('\n')
}
