import type { ShapeNode } from '../types.js'
import { isSafeKey, nameAllocator } from './naming.js'
import type { CodegenSnapshot } from './types.js'

const HEADER =
  '// Generated by schemind — do not edit by hand.\n// Run `schm codegen --target ts` to regenerate.\n'

/** Options for {@link generateTypeScript}. */
export interface TypeScriptOptions {
  /** Appended to each generated type name. Default `'Response'`. */
  suffix?: string
  /** Indent unit. Default two spaces. */
  indent?: string
}

/**
 * Render a single {@link ShapeNode} as a TypeScript type expression.
 *
 * - scalars → `string` / `number` / `boolean` / `null`
 * - array → `T[]` (or `Array<T>` when `T` is a union)
 * - object → a pretty-printed `{ … }` literal (keys quoted only when needed)
 * - union → `A | B` (with `null` moved last); the empty union → `unknown`
 */
export function shapeToTypeScript(node: ShapeNode, indent = '  '): string {
  return render(node, indent, 0)
}

function render(node: ShapeNode, indent: string, depth: number): string {
  switch (node.kind) {
    case 'scalar':
      return node.type
    case 'array': {
      const item = render(node.items, indent, depth)
      return node.items.kind === 'union' && node.items.types.length > 1
        ? `Array<${item}>`
        : `${item}[]`
    }
    case 'union': {
      if (node.types.length === 0) return 'unknown'
      const ordered = [...node.types].sort(nullLast)
      return ordered.map((t) => render(t, indent, depth)).join(' | ')
    }
    case 'object': {
      const keys = Object.keys(node.fields)
      if (keys.length === 0) return 'Record<string, never>'
      const pad = indent.repeat(depth + 1)
      const close = indent.repeat(depth)
      const lines = keys.map((key) => {
        const k = isSafeKey(key) ? key : JSON.stringify(key)
        return `${pad}${k}: ${render(node.fields[key]!, indent, depth + 1)}`
      })
      return `{\n${lines.join('\n')}\n${close}}`
    }
  }
}

function nullLast(a: ShapeNode, b: ShapeNode): number {
  const an = a.kind === 'scalar' && a.type === 'null' ? 1 : 0
  const bn = b.kind === 'scalar' && b.type === 'null' ? 1 : 0
  return an - bn
}

/**
 * Generate a TypeScript module of `export`ed interfaces/types — one per
 * endpoint — from observed snapshots. The killer feature: real API types with
 * no hand-written spec.
 */
export function generateTypeScript(
  snapshots: readonly CodegenSnapshot[],
  options: TypeScriptOptions = {},
): string {
  const indent = options.indent ?? '  '
  const suffix = options.suffix ?? 'Response'
  const allocate = nameAllocator()

  const blocks = snapshots.map((snap) => {
    const name = allocate(snap.endpoint, suffix)
    const body = render(snap.shape, indent, 0)
    const decl =
      snap.shape.kind === 'object'
        ? `export interface ${name} ${body}`
        : `export type ${name} = ${body}`
    return `/** \`${snap.endpoint}\` */\n${decl}`
  })

  return `${HEADER}\n${blocks.join('\n\n')}\n`
}
